CREATE DATABASE project;

CREATE USER akshay WITH PASSWORD 'database';
CREATE USER mohit WITH PASSWORD 'database';

GRANT ALL PRIVILEGES ON DATABASE project TO akshay;
GRANT ALL PRIVILEGES ON DATABASE project TO mohit;
